// easy_pos/public/js/pos/components/ItemGroup.vue
<template>
    <div class="card m-3 text-center hover-border-green" style="width: 100px; height: 130px;" v-for="group in itemGroups"
        :key="group.name">
        <img :src="group.image" class="card-img-top mx-auto mt-3"
            style="width: 70px; height: 60px; object-fit: contain;" />
        <div class="card-body p-2 d-flex flex-column justify-content-center">
            <p class="card-text mt-2">{{ group.name }}</p>
        </div>
    </div>

</template>

<script>
export default {
    data() {
        return {
            loading: false,
            itemGroups: [],
        }
    },
    created() {
        this.getItemGroups();
    },
    methods: {
        getItemGroups() {
            this.loading = true;
            frappe.call({
                method: "easy_pos.api.item.get_item_groups",
                callback: (resp) => {
                    this.loading = false;
                    this.itemGroups = resp?.message || [];
                }
            });
        }
    }
}
</script>

// posapp/src/components/ItemGroup/index.jsx
import { useEffect, useState } from "react";
import "./style.css"
import { fetchItemGroups } from "../../api/ItemGroup";

const ItemGroup = () => {
  const [itemGroups, setItemGroups] = useState([]);

  const getItemGroups = () => {
    fetchItemGroups().then(data => {
      setItemGroups(data)
    })
  }

  useEffect(() => {
    getItemGroups()
  }, [])

  return (
    <div
      className="sidebar mx-0 d-none d-lg-block"
      style={{ borderRight: "1px solid #E6EAED", width: "9%", maxHeight: "90vh", overflowY: "scroll" }}
    >
      <ul className="d-flex flex-column nav">
        {itemGroups.length > 0 &&
          itemGroups.map((row, idx) => {
            return (
              <li className="nav-item mt-3" key={idx}>
                <div className="card align-items-center text-center item-group-card">
                  <img
                    src={row.image}
                    alt={row.item_code}
                    height={50}
                    width={50}
                  />
                  <p className="mb-0">{row.item_group}</p>
                </div>
              </li>
            );
          })}
      </ul>
    </div>
  );
};

export default ItemGroup;
